# Generated by Django 2.2.2 on 2019-11-01 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('child', models.CharField(max_length=100)),
                ('pos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('neg', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
