# Generated by Django 2.2.2 on 2019-12-01 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TupleCopy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('parent', models.CharField(max_length=100)),
                ('child', models.CharField(max_length=100)),
                ('pos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('neg', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
