# Generated by Django 2.2.2 on 2019-12-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tuplecopy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuplecopy',
            old_name='neg',
            new_name='sump',
        ),
        migrations.RemoveField(
            model_name='tuplecopy',
            name='pos',
        ),
    ]
