# Generated by Django 2.2.2 on 2019-12-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191201_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TupleCopy',
        ),
    ]
