# Generated by Django 2.2.2 on 2019-12-02 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191202_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpairs',
            name='verifyNumber',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
